name: check

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  schedule:
    - cron: "0 8 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test using python ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.12"
          - "3.13"
          - "3.14"
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Create a virtual environment and install dependencies
        run: uv sync --locked --all-extras --no-default-groups --group=test --python=${{ matrix.py }}
      - name: Run tests
        run: uv run pytest

  check:
    name: Check tox environment ${{ matrix.tox_env }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        tox_env:
          - docs
          - package
          - style
          - type
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Install tox with tox-uv
        run: uv tool install --python-preference=only-managed --python=3.12 tox --with tox-uv
      - name: Setup tox environment
        run: tox run -vv --notest --skip-missing-interpreters=false -e ${{ matrix.tox_env }}
      - name: Run commands
        run: tox run --skip-pkg-install -e ${{ matrix.tox_env }}

  coverage:
    name: Report coverage
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Create a virtual environment and sync all required dependencies
        run: uv sync --locked --all-extras --no-default-groups --group=test --python=3.12
      - name: Run pytest using coverage
        run: uv run coverage run -m pytest
      - name: Combine coverage data
        run: uv run coverage combine
      - name: Report and write to summary
        run: uv run coverage report --format=markdown >> $GITHUB_STEP_SUMMARY